version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: odot-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - odot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  migrations:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.migrations
    container_name: odot-migrations-dev
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ./sql/migrations:/app/migrations
    networks:
      - odot-network
    restart: on-failure

  # API Server (Go backend only)
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: odot-api-dev
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - odot-network
    restart: on-failure

  # Frontend Dev Server (React/Vite)
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: odot-frontend-dev
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app/ui
      - /app/ui/node_modules # Preserve node_modules in container
    networks:
      - odot-network
    restart: on-failure
    command: ["sh", "-c", "cd ui && bun install && bun run dev --host 0.0.0.0"]

volumes:
  postgres_data:

networks:
  odot-network:
    driver: bridge
