# Dockerfile.migrations
FROM golang:1.24-alpine

WORKDIR /app

# Install goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Copy migrations
COPY ./sql/migrations /app/migrations


# Run migrations
CMD ["goose", "-dir", "migrations", "postgres", "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable", "up"]
