// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check the health of the application and its dependencies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get application health status",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Return a simplified health status",
                        "name": "simple",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Simple status when simple=true and healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Simple status when simple=true and unhealthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.HealthStatus": {
            "type": "object",
            "properties": {
                "dependencies": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "environment": {
                    "type": "string"
                },
                "go_version": {
                    "type": "string"
                },
                "memory": {
                    "$ref": "#/definitions/handlers.MemStats"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "handlers.MemStats": {
            "type": "object",
            "properties": {
                "alloc": {
                    "description": "Bytes allocated and not yet freed",
                    "type": "integer"
                },
                "num_gc": {
                    "description": "Number of completed GC cycles",
                    "type": "integer"
                },
                "sys": {
                    "description": "Bytes obtained from system",
                    "type": "integer"
                },
                "total_alloc": {
                    "description": "Bytes allocated (even if freed)",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
