// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	CommentID int32              `json:"commentId"`
	TodoID    int32              `json:"todoId"`
	UserID    int32              `json:"userId"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type NotificationQueue struct {
	NotificationID   int32              `json:"notificationId"`
	TodoID           int32              `json:"todoId"`
	UserID           int32              `json:"userId"`
	ScheduledFor     pgtype.Timestamptz `json:"scheduledFor"`
	NotificationType pgtype.Text        `json:"notificationType"`
	Sent             pgtype.Bool        `json:"sent"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}

type Project struct {
	ProjectID       int32              `json:"projectId"`
	UserID          int32              `json:"userId"`
	ParentProjectID pgtype.Int4        `json:"parentProjectId"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	Color           pgtype.Text        `json:"color"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

type PushSubscription struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"userId"`
	Endpoint  string             `json:"endpoint"`
	P256dhKey string             `json:"p256dhKey"`
	AuthKey   string             `json:"authKey"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	IsActive  pgtype.Bool        `json:"isActive"`
}

type RefreshToken struct {
	TokenID    int32              `json:"tokenId"`
	UserID     int32              `json:"userId"`
	TokenHash  string             `json:"tokenHash"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	LastUsedAt pgtype.Timestamptz `json:"lastUsedAt"`
	IsRevoked  pgtype.Bool        `json:"isRevoked"`
}

type Tag struct {
	TagID     int32              `json:"tagId"`
	UserID    int32              `json:"userId"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type TemplateTag struct {
	TemplateID int32 `json:"templateId"`
	TagID      int32 `json:"tagId"`
}

type Todo struct {
	TodoID         int32              `json:"todoId"`
	UserID         int32              `json:"userId"`
	TemplateID     pgtype.Int4        `json:"templateId"`
	ProjectID      pgtype.Int4        `json:"projectId"`
	ParentTodoID   pgtype.Int4        `json:"parentTodoId"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	IsCompleted    pgtype.Bool        `json:"isCompleted"`
	ScheduledDate  pgtype.Timestamptz `json:"scheduledDate"`
	DurationMin    pgtype.Int4        `json:"durationMin"`
	Priority       pgtype.Int4        `json:"priority"`
	IsModified     pgtype.Bool        `json:"isModified"`
	ModifiedFields []byte             `json:"modifiedFields"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt      pgtype.Timestamptz `json:"updatedAt"`
	CompletedAt    pgtype.Timestamptz `json:"completedAt"`
}

type TodoTag struct {
	TodoID int32 `json:"todoId"`
	TagID  int32 `json:"tagId"`
}

type TodoTemplate struct {
	TemplateID  int32              `json:"templateId"`
	UserID      int32              `json:"userId"`
	ProjectID   pgtype.Int4        `json:"projectId"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DurationMin pgtype.Int4        `json:"durationMin"`
	Priority    pgtype.Int4        `json:"priority"`
	Rrule       string             `json:"rrule"`
	Dtstart     pgtype.Timestamptz `json:"dtstart"`
	UntilDate   pgtype.Timestamptz `json:"untilDate"`
	IsActive    pgtype.Bool        `json:"isActive"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	UserID            int32              `json:"userId"`
	Email             string             `json:"email"`
	PasswordHash      pgtype.Text        `json:"passwordHash"`
	GoogleID          pgtype.Text        `json:"googleId"`
	ProfilePictureUrl pgtype.Text        `json:"profilePictureUrl"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}
