// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notification_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notification_queue (
    todo_id, user_id, scheduled_for, notification_type
) VALUES (
    $1, $2, $3, $4
) RETURNING notification_id, todo_id, user_id, scheduled_for, notification_type, sent, created_at
`

type CreateNotificationParams struct {
	TodoID           int32              `json:"todoId"`
	UserID           int32              `json:"userId"`
	ScheduledFor     pgtype.Timestamptz `json:"scheduledFor"`
	NotificationType pgtype.Text        `json:"notificationType"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (NotificationQueue, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.TodoID,
		arg.UserID,
		arg.ScheduledFor,
		arg.NotificationType,
	)
	var i NotificationQueue
	err := row.Scan(
		&i.NotificationID,
		&i.TodoID,
		&i.UserID,
		&i.ScheduledFor,
		&i.NotificationType,
		&i.Sent,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notification_queue
WHERE notification_id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, notificationID int32) error {
	_, err := q.db.Exec(ctx, deleteNotification, notificationID)
	return err
}

const getNotificationsWithTodoAndSubscriptions = `-- name: GetNotificationsWithTodoAndSubscriptions :many
SELECT 
    nq.notification_id,
    nq.todo_id,
    nq.user_id,
    nq.scheduled_for,
    nq.notification_type,
    nq.sent,
    nq.created_at,
    t.title as todo_title,
    t.description as todo_description,
    t.scheduled_date as todo_scheduled_date,
    t.duration_min as todo_duration_min,
    t.priority as todo_priority,
    ps.id as subscription_id,
    ps.endpoint,
    ps.p256dh_key,
    ps.auth_key
FROM notification_queue nq
JOIN todos t ON nq.todo_id = t.todo_id
JOIN push_subscriptions ps ON nq.user_id = ps.user_id AND ps.is_active = TRUE
WHERE nq.scheduled_for BETWEEN $1 AND $2 AND nq.sent = FALSE
ORDER BY nq.scheduled_for ASC
`

type GetNotificationsWithTodoAndSubscriptionsParams struct {
	ScheduledFor   pgtype.Timestamptz `json:"scheduledFor"`
	ScheduledFor_2 pgtype.Timestamptz `json:"scheduledFor2"`
}

type GetNotificationsWithTodoAndSubscriptionsRow struct {
	NotificationID    int32              `json:"notificationId"`
	TodoID            int32              `json:"todoId"`
	UserID            int32              `json:"userId"`
	ScheduledFor      pgtype.Timestamptz `json:"scheduledFor"`
	NotificationType  pgtype.Text        `json:"notificationType"`
	Sent              pgtype.Bool        `json:"sent"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	TodoTitle         string             `json:"todoTitle"`
	TodoDescription   pgtype.Text        `json:"todoDescription"`
	TodoScheduledDate pgtype.Timestamptz `json:"todoScheduledDate"`
	TodoDurationMin   pgtype.Int4        `json:"todoDurationMin"`
	TodoPriority      pgtype.Int4        `json:"todoPriority"`
	SubscriptionID    int32              `json:"subscriptionId"`
	Endpoint          string             `json:"endpoint"`
	P256dhKey         string             `json:"p256dhKey"`
	AuthKey           string             `json:"authKey"`
}

func (q *Queries) GetNotificationsWithTodoAndSubscriptions(ctx context.Context, arg GetNotificationsWithTodoAndSubscriptionsParams) ([]GetNotificationsWithTodoAndSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getNotificationsWithTodoAndSubscriptions, arg.ScheduledFor, arg.ScheduledFor_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNotificationsWithTodoAndSubscriptionsRow{}
	for rows.Next() {
		var i GetNotificationsWithTodoAndSubscriptionsRow
		if err := rows.Scan(
			&i.NotificationID,
			&i.TodoID,
			&i.UserID,
			&i.ScheduledFor,
			&i.NotificationType,
			&i.Sent,
			&i.CreatedAt,
			&i.TodoTitle,
			&i.TodoDescription,
			&i.TodoScheduledDate,
			&i.TodoDurationMin,
			&i.TodoPriority,
			&i.SubscriptionID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingNotifications = `-- name: GetPendingNotifications :many
SELECT notification_id, todo_id, user_id, scheduled_for, notification_type, sent, created_at FROM notification_queue
WHERE scheduled_for <= NOW() AND sent = FALSE
ORDER BY scheduled_for ASC
`

func (q *Queries) GetPendingNotifications(ctx context.Context) ([]NotificationQueue, error) {
	rows, err := q.db.Query(ctx, getPendingNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationQueue{}
	for rows.Next() {
		var i NotificationQueue
		if err := rows.Scan(
			&i.NotificationID,
			&i.TodoID,
			&i.UserID,
			&i.ScheduledFor,
			&i.NotificationType,
			&i.Sent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsentNotificationsInRange = `-- name: GetUnsentNotificationsInRange :many
SELECT notification_id, todo_id, user_id, scheduled_for, notification_type, sent, created_at FROM notification_queue
WHERE scheduled_for BETWEEN $1 AND $2 AND sent = FALSE
ORDER BY scheduled_for ASC
`

type GetUnsentNotificationsInRangeParams struct {
	ScheduledFor   pgtype.Timestamptz `json:"scheduledFor"`
	ScheduledFor_2 pgtype.Timestamptz `json:"scheduledFor2"`
}

func (q *Queries) GetUnsentNotificationsInRange(ctx context.Context, arg GetUnsentNotificationsInRangeParams) ([]NotificationQueue, error) {
	rows, err := q.db.Query(ctx, getUnsentNotificationsInRange, arg.ScheduledFor, arg.ScheduledFor_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationQueue{}
	for rows.Next() {
		var i NotificationQueue
		if err := rows.Scan(
			&i.NotificationID,
			&i.TodoID,
			&i.UserID,
			&i.ScheduledFor,
			&i.NotificationType,
			&i.Sent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notification_queue
SET sent = TRUE
WHERE notification_id = $1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, notificationID int32) error {
	_, err := q.db.Exec(ctx, markNotificationSent, notificationID)
	return err
}
