// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: push_subscriptions.sql

package db

import (
	"context"
)

const cleanupOldSubscriptions = `-- name: CleanupOldSubscriptions :exec
DELETE FROM push_subscriptions
WHERE created_at < NOW() - INTERVAL '30 days' AND is_active = FALSE
`

func (q *Queries) CleanupOldSubscriptions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldSubscriptions)
	return err
}

const createPushSubscription = `-- name: CreatePushSubscription :one
INSERT INTO push_subscriptions (
    user_id, endpoint, p256dh_key, auth_key
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (user_id, endpoint)
DO UPDATE SET
    p256dh_key = EXCLUDED.p256dh_key,
    auth_key = EXCLUDED.auth_key,
    updated_at = NOW(),
    is_active = TRUE
RETURNING id, user_id, endpoint, p256dh_key, auth_key, created_at, updated_at, is_active
`

type CreatePushSubscriptionParams struct {
	UserID    int32  `json:"userId"`
	Endpoint  string `json:"endpoint"`
	P256dhKey string `json:"p256dhKey"`
	AuthKey   string `json:"authKey"`
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, createPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dhKey,
		arg.AuthKey,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dhKey,
		&i.AuthKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
UPDATE push_subscriptions
SET is_active = FALSE, updated_at = NOW()
WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionParams struct {
	UserID   int32  `json:"userId"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.UserID, arg.Endpoint)
	return err
}

const getUserPushSubscriptions = `-- name: GetUserPushSubscriptions :many
SELECT id, user_id, endpoint, p256dh_key, auth_key, created_at, updated_at, is_active FROM push_subscriptions
WHERE user_id = $1 AND is_active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) GetUserPushSubscriptions(ctx context.Context, userID int32) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, getUserPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionInactive = `-- name: MarkSubscriptionInactive :exec
UPDATE push_subscriptions
SET is_active = FALSE, updated_at = NOW()
WHERE user_id = $1 AND endpoint = $2
`

type MarkSubscriptionInactiveParams struct {
	UserID   int32  `json:"userId"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) MarkSubscriptionInactive(ctx context.Context, arg MarkSubscriptionInactiveParams) error {
	_, err := q.db.Exec(ctx, markSubscriptionInactive, arg.UserID, arg.Endpoint)
	return err
}
