// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (user_id, name, color)
VALUES ($1, $2, $3)
RETURNING tag_id, user_id, name, color, created_at
`

type CreateTagParams struct {
	UserID int32       `json:"userId"`
	Name   string      `json:"name"`
	Color  pgtype.Text `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.UserID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.TagID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE tag_id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, tagID int32) error {
	_, err := q.db.Exec(ctx, deleteTag, tagID)
	return err
}

const getTag = `-- name: GetTag :one
SELECT tag_id, user_id, name, color, created_at FROM tags
WHERE tag_id = $1
`

func (q *Queries) GetTag(ctx context.Context, tagID int32) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, tagID)
	var i Tag
	err := row.Scan(
		&i.TagID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT tag_id, user_id, name, color, created_at FROM tags
WHERE user_id = $1 AND name = $2
`

type GetTagByNameParams struct {
	UserID int32  `json:"userId"`
	Name   string `json:"name"`
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.TagID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT tag_id, user_id, name, color, created_at FROM tags
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context, userID int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.TagID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $2, color = $3
WHERE tag_id = $1
RETURNING tag_id, user_id, name, color, created_at
`

type UpdateTagParams struct {
	TagID int32       `json:"tagId"`
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.TagID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.TagID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
