// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id FROM "User" WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	err := row.Scan(&id)
	return id, err
}
